### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by Slluxx** [mstellmacher/jquery-lwd#2]
im looking for something like that in a long long time. i had no clue how this type of site is called or with what it was made. 

What would i need to make desktop icons and order them in grid etc? do you have useful urls or other examples which i could take a look at?

By the way i also noticed some broken images. if you open alot of windows, the up and down arrow images doesnt exist.

Best regards,
Calvin

**Comment by mstellmacher** [comment]
This will on on top of my head so forgive me if the solution is no perfect:

I would go about adding Desktop-Items in this way:

Make a new CSS-class for desktop-icons. For exmaple ".desktop-icon".
Setup the CSS for the class ".desktop-icon" with:
```
.desktop-icon {
    display: inline-block;
    height: 32px;
    width: 32px;
    margin: 16px;
}
```
And then you can place a 32x32 &lt;img&gt;-Tag as your icon into a &lt;div&gt;-element with the said ".desktop-icon" class. This would automatically align them in a grid from left to right and top to down.

For example:
```
<div class="desktop-icon"><img src="/img/myicon1.png"></div>
<div class="desktop-icon"><img src="/img/myicon2.png"></div>
<div class="desktop-icon"><img src="/img/myicon3.png"></div>
<div class="desktop-icon"><img src="/img/myicon4.png"></div>
```

I will look into the issue with the icons but I could not replicate it so far (300 windows opened).

**Comment by mstellmacher** [comment]
I could not replicate the issue with missing icons. Tested every browser and every device I could get my hands on -> closed

**Comment by Slluxx** [comment]
Havent looked into it in a very long time but it might be some adblock extension that prevents icons from being loaded
